// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ABadge: typeof import('ant-design-vue/es')['Badge']
    AddMaterialCard: typeof import('./src/components/AddMaterialCard.vue')['default']
    AddMealModal: typeof import('./src/components/AddMealModal.vue')['default']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputNumber: typeof import('ant-design-vue/es')['InputNumber']
    AppModal: typeof import('./src/components/AppModal.vue')['default']
    AppNav: typeof import('./src/components/AppNav.vue')['default']
    AppNoti: typeof import('./src/components/AppNoti.vue')['default']
    AppNotis: typeof import('./src/components/AppNotis.vue')['default']
    ASkeleton: typeof import('ant-design-vue/es')['Skeleton']
    ASlider: typeof import('ant-design-vue/es')['Slider']
    CaloriesStatsCard: typeof import('./src/components/CaloriesStatsCard.vue')['default']
    DailyMeals: typeof import('./src/components/DailyMeals.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    MaterialBoard: typeof import('./src/components/MaterialBoard.vue')['default']
    MaterialCard: typeof import('./src/components/MaterialCard.vue')['default']
    MaterialList: typeof import('./src/components/MaterialList.vue')['default']
    MealCard: typeof import('./src/components/MealCard.vue')['default']
    MealsTab: typeof import('./src/components/MealsTab.vue')['default']
    RecentAddedBoard: typeof import('./src/components/RecentAddedBoard.vue')['default']
    RecentMeals: typeof import('./src/components/RecentMeals.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    TDEECalculator: typeof import('./src/components/TDEECalculator.vue')['default']
  }
}
