export default [
  {
    id: 10001,
    name: "年糕",
    caloriesPerHundredGram: 220,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/308/308556.png",
    default: true,
    deleted: false,
  },
  {
    id: 0,
    name: "其他",
    caloriesPerHundredGram: 100,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1046/1046857.png",
    default: true,
    deleted: false,
  },
  {
    id: 1,
    name: "米饭",
    caloriesPerHundredGram: 116,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/651/651589.png",
    default: true,
    deleted: false,
  },
  {
    id: 2,
    name: "鸡蛋",
    caloriesPerHundredGram: 139,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1951/1951379.png",
    default: true,
    deleted: false,
  },
  {
    id: 3,
    name: "大白菜",
    caloriesPerHundredGram: 20,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/884/884316.png",
    default: true,
    deleted: false,
  },
  {
    id: 4,
    name: "卷心菜",
    caloriesPerHundredGram: 24,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/765/765618.png",
    default: true,
    deleted: false,
  },
  {
    id: 5,
    name: "猪肉（痩）",
    caloriesPerHundredGram: 143,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1391/1391399.png",
    default: true,
    deleted: false,
  },
  {
    id: 6,
    name: "猪肉（肥）",
    caloriesPerHundredGram: 807,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1391/1391399.png",
    default: true,
    deleted: false,
  },
  {
    id: 7,
    name: "牛肉",
    caloriesPerHundredGram: 125,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/3143/3143643.png",
    default: true,
    deleted: false,
  },
  {
    id: 8,
    name: "鸡肉",
    caloriesPerHundredGram: 167,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1046/1046751.png",
    default: true,
    deleted: false,
  },
  {
    id: 9,
    name: "青菜",
    caloriesPerHundredGram: 19,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2503/2503919.png",
    default: true,
    deleted: false,
  },
  {
    id: 10,
    name: "辣椒",
    caloriesPerHundredGram: 62,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2156/2156631.png",
    default: true,
    deleted: false,
  },
  {
    id: 11,
    name: "葡萄",
    caloriesPerHundredGram: 45,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/3137/3137056.png",
    default: true,
    deleted: false,
  },
  {
    id: 12,
    name: "香蕉",
    caloriesPerHundredGram: 93,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2083/2083677.png",
    default: true,
    deleted: false,
  },
  {
    id: 13,
    name: "牛奶",
    caloriesPerHundredGram: 66,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/869/869664.png",
    default: true,
    deleted: false,
  },
  {
    id: 14,
    name: "面条",
    caloriesPerHundredGram: 300,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2836/2836607.png",
    default: true,
    deleted: false,
  },
  {
    id: 15,
    name: "西瓜",
    caloriesPerHundredGram: 32,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/5582/5582706.png",
    default: true,
    deleted: false,
  },
  {
    id: 16,
    name: "豆腐干",
    caloriesPerHundredGram: 197,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/454/454595.png",
    default: true,
    deleted: false,
  },
  {
    id: 17,
    name: "青椒",
    caloriesPerHundredGram: 22,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/7100/7100438.png",
    default: true,
    deleted: false,
  },
  {
    id: 18,
    name: "千张",
    caloriesPerHundredGram: 262,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/6447/6447284.png",
    default: true,
    deleted: false,
  },
  {
    id: 19,
    name: "羊肉（痩）",
    caloriesPerHundredGram: 118,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2711/2711887.png",
    default: true,
    deleted: false,
  },
  {
    id: 20,
    name: "豌豆",
    caloriesPerHundredGram: 111,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2314/2314660.png",
    default: true,
    deleted: false,
  },
];
