export default [
  {
    id: 10001,
    name: "年糕",
    caloriesPerHundredGram: 220,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/308/308556.png",
    default: true,
    deleted: false,
  },
  {
    id: 1,
    name: "米饭",
    caloriesPerHundredGram: 116,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/651/651589.png",
    default: true,
    deleted: false,
  },
  {
    id: 2,
    name: "鸡蛋",
    caloriesPerHundredGram: 139,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1951/1951379.png",
    default: true,
    deleted: false,
  },
  {
    id: 3,
    name: "大白菜",
    caloriesPerHundredGram: 20,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/884/884316.png",
    default: true,
    deleted: false,
  },
  {
    id: 4,
    name: "卷心菜",
    caloriesPerHundredGram: 24,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/765/765618.png",
    default: true,
    deleted: false,
  },
  {
    id: 5,
    name: "猪肉（痩）",
    caloriesPerHundredGram: 143,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1391/1391399.png",
    default: true,
    deleted: false,
  },
  {
    id: 6,
    name: "猪肉（肥）",
    caloriesPerHundredGram: 807,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1391/1391399.png",
    default: true,
    deleted: false,
  },
  {
    id: 7,
    name: "牛肉",
    caloriesPerHundredGram: 125,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/3143/3143643.png",
    default: true,
    deleted: false,
  },
  {
    id: 8,
    name: "鸡肉",
    caloriesPerHundredGram: 167,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/1046/1046751.png",
    default: true,
    deleted: false,
  },
  {
    id: 9,
    name: "青菜",
    caloriesPerHundredGram: 19,
    imgUrl: "https://cdn-icons-png.flaticon.com/512/2503/2503919.png",
    default: true,
    deleted: false,
  },
];
